document.write('<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js%22%3E</script>');
document.write('<script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.net.min.js%22%3E</script>');
document.write('<script>');
document.write('VANTA.NET({');
document.write('  el: "#animation-bg",');
document.write('  mouseControls: true,');
document.write('  touchControls: true,');
document.write('  gyroControls: false,');
document.write('  minHeight: 200.00,');
document.write('  minWidth: 200.00,');
document.write('  scale: 1.00,');
document.write('  scaleMobile: 1.00,');
document.write('  color: 0xea0d41,');
document.write('  backgroundColor: 0x0,');
document.write('  points: 9.00');
document.write('})');
document.write('</script>');
